/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelayRouteImport } from './routes/_authenticated/relay'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated/api-docs'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppsAppIdRouteImport } from './routes/_authenticated/apps.$appId'
import { Route as ApiPublicWebhookSmsRouteImport } from './routes/api/public/webhook/sms'
import { Route as ApiPublicV1RelayPingRouteImport } from './routes/api/public/v1/relay/ping'
import { Route as ApiPublicV1LicenseVerifyRouteImport } from './routes/api/public/v1/license/verify'
import { Route as ApiPublicV1CheckoutInitRouteImport } from './routes/api/public/v1/checkout/init'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelayRoute = AuthenticatedRelayRouteImport.update({
  id: '/relay',
  path: '/relay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsAppIdRoute = AuthenticatedAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhookSmsRoute = ApiPublicWebhookSmsRouteImport.update({
  id: '/api/public/webhook/sms',
  path: '/api/public/webhook/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RelayPingRoute = ApiPublicV1RelayPingRouteImport.update({
  id: '/api/public/v1/relay/ping',
  path: '/api/public/v1/relay/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1LicenseVerifyRoute =
  ApiPublicV1LicenseVerifyRouteImport.update({
    id: '/api/public/v1/license/verify',
    path: '/api/public/v1/license/verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1CheckoutInitRoute = ApiPublicV1CheckoutInitRouteImport.update({
  id: '/api/public/v1/checkout/init',
  path: '/api/public/v1/checkout/init',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/relay': typeof AuthenticatedRelayRoute
  '/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/api/public/webhook/sms': typeof ApiPublicWebhookSmsRoute
  '/api/public/v1/checkout/init': typeof ApiPublicV1CheckoutInitRoute
  '/api/public/v1/license/verify': typeof ApiPublicV1LicenseVerifyRoute
  '/api/public/v1/relay/ping': typeof ApiPublicV1RelayPingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/relay': typeof AuthenticatedRelayRoute
  '/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/api/public/webhook/sms': typeof ApiPublicWebhookSmsRoute
  '/api/public/v1/checkout/init': typeof ApiPublicV1CheckoutInitRoute
  '/api/public/v1/license/verify': typeof ApiPublicV1LicenseVerifyRoute
  '/api/public/v1/relay/ping': typeof ApiPublicV1RelayPingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/relay': typeof AuthenticatedRelayRoute
  '/_authenticated/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/api/public/webhook/sms': typeof ApiPublicWebhookSmsRoute
  '/api/public/v1/checkout/init': typeof ApiPublicV1CheckoutInitRoute
  '/api/public/v1/license/verify': typeof ApiPublicV1LicenseVerifyRoute
  '/api/public/v1/relay/ping': typeof ApiPublicV1RelayPingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/api-docs'
    | '/dashboard'
    | '/relay'
    | '/apps/$appId'
    | '/api/public/webhook/sms'
    | '/api/public/v1/checkout/init'
    | '/api/public/v1/license/verify'
    | '/api/public/v1/relay/ping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/api-docs'
    | '/dashboard'
    | '/relay'
    | '/apps/$appId'
    | '/api/public/webhook/sms'
    | '/api/public/v1/checkout/init'
    | '/api/public/v1/license/verify'
    | '/api/public/v1/relay/ping'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/api-docs'
    | '/_authenticated/dashboard'
    | '/_authenticated/relay'
    | '/_authenticated/apps/$appId'
    | '/api/public/webhook/sms'
    | '/api/public/v1/checkout/init'
    | '/api/public/v1/license/verify'
    | '/api/public/v1/relay/ping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicWebhookSmsRoute: typeof ApiPublicWebhookSmsRoute
  ApiPublicV1CheckoutInitRoute: typeof ApiPublicV1CheckoutInitRoute
  ApiPublicV1LicenseVerifyRoute: typeof ApiPublicV1LicenseVerifyRoute
  ApiPublicV1RelayPingRoute: typeof ApiPublicV1RelayPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relay': {
      id: '/_authenticated/relay'
      path: '/relay'
      fullPath: '/relay'
      preLoaderRoute: typeof AuthenticatedRelayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/$appId': {
      id: '/_authenticated/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AuthenticatedAppsAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhook/sms': {
      id: '/api/public/webhook/sms'
      path: '/api/public/webhook/sms'
      fullPath: '/api/public/webhook/sms'
      preLoaderRoute: typeof ApiPublicWebhookSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/relay/ping': {
      id: '/api/public/v1/relay/ping'
      path: '/api/public/v1/relay/ping'
      fullPath: '/api/public/v1/relay/ping'
      preLoaderRoute: typeof ApiPublicV1RelayPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/license/verify': {
      id: '/api/public/v1/license/verify'
      path: '/api/public/v1/license/verify'
      fullPath: '/api/public/v1/license/verify'
      preLoaderRoute: typeof ApiPublicV1LicenseVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/checkout/init': {
      id: '/api/public/v1/checkout/init'
      path: '/api/public/v1/checkout/init'
      fullPath: '/api/public/v1/checkout/init'
      preLoaderRoute: typeof ApiPublicV1CheckoutInitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRelayRoute: typeof AuthenticatedRelayRoute
  AuthenticatedAppsAppIdRoute: typeof AuthenticatedAppsAppIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRelayRoute: AuthenticatedRelayRoute,
  AuthenticatedAppsAppIdRoute: AuthenticatedAppsAppIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicWebhookSmsRoute: ApiPublicWebhookSmsRoute,
  ApiPublicV1CheckoutInitRoute: ApiPublicV1CheckoutInitRoute,
  ApiPublicV1LicenseVerifyRoute: ApiPublicV1LicenseVerifyRoute,
  ApiPublicV1RelayPingRoute: ApiPublicV1RelayPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
